### ISSUE TITLE
Aggiungere la possibilità di specificare la percentuale di RAM da utilizzare come Heap Java

### ISSUE THREAD

**Issue by criluc** [consiglionazionaledellericerche/epas#255]
Il default prevede che la JVM utilizzi solo un quarto della RAM del container (o dell'host ospitante il container se la RAM del container non è limitata).

Il parametro da utilizzare per controllare il comportamento della JVM è -XX:MaxRAMPercentage

Per limitare la RAM del container è possibile utilizzare una configurazione tipo
```
  epas:
    deploy:
      resources:
        limits:
          memory: 16G
```
